# Generated by Django 5.0.2 on 2024-03-03 13:15

import apps.accounts_api_v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api_v1', '0002_alter_user_options_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter a username containing 4-20 characters. It can only contain letters, hyphens, and digits.', max_length=20, unique=True, validators=[apps.accounts_api_v1.validators.validate_username], verbose_name='username'),
        ),
    ]
