# Generated by Django 5.0.2 on 2024-03-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='close',
            field=models.DecimalField(decimal_places=18, help_text='The closing price.', max_digits=36, verbose_name='close'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high',
            field=models.DecimalField(decimal_places=18, help_text='The highest price.', max_digits=36, verbose_name='high'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low',
            field=models.DecimalField(decimal_places=18, help_text='The lowest price.', max_digits=36, verbose_name='low'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open',
            field=models.DecimalField(decimal_places=18, help_text='The opening price.', max_digits=36, verbose_name='open'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='stocks_api_v1.stock', verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='value',
            field=models.DecimalField(decimal_places=18, help_text='The total value of trades during the candle period.', max_digits=36, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.DecimalField(decimal_places=18, help_text='The total volume of trades during the candle period.', max_digits=36, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currencyid',
            field=models.CharField(help_text='The currency of settlement for the instrument.', max_length=10, null=True, verbose_name='currency ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='decimals',
            field=models.PositiveSmallIntegerField(default=0, help_text='The number of decimal places of the fractional part of the number. It is used to format the values of fields with the DECIMAL type.', null=True, verbose_name='decimals'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='faceunit',
            field=models.CharField(help_text='The code of the currency in which the nominal value of the security is expressed.', max_length=10, null=True, verbose_name='faceunit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='facevalue',
            field=models.DecimalField(decimal_places=17, help_text='The nominal value of one security at the current date.', max_digits=34, null=True, verbose_name='facevalue'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin',
            field=models.CharField(help_text='The international identification code of the security.', max_length=20, null=True, verbose_name='isin'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issuesize',
            field=models.PositiveBigIntegerField(help_text='The number of securities in the issue.', null=True, verbose_name='issuesize'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='listlevel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1, help_text='The listing level.', null=True, verbose_name='listlevel'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lotsize',
            field=models.PositiveIntegerField(help_text='The number of securities in one standard lot.', null=True, verbose_name='lotsize'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minstep',
            field=models.DecimalField(decimal_places=10, help_text='The minimum possible difference between the prices indicated in the bids for the purchase/sale of securities', max_digits=20, null=True, verbose_name='min step'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prevlegalcloseprice',
            field=models.DecimalField(decimal_places=10, default=0, help_text='The official closing price of the previous day, calculated in accordance with the trading rules as the weighted average price of transactions for the last 10 minutes of the main session, including transactions of the post-trading period or the closing auction.', max_digits=20, null=True, verbose_name='prev legal close price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prevprice',
            field=models.DecimalField(decimal_places=10, default=0, help_text='The price of the last trade of the previous day.', max_digits=20, null=True, verbose_name='prevprice'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='secname',
            field=models.CharField(help_text='The name of the financial instrument.', max_length=50, null=True, verbose_name='secname'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sectype',
            field=models.CharField(choices=[('1', 'The security is ordinary'), ('2', 'The security is privileged'), ('3', 'Government bonds'), ('4', 'Regional bonds'), ('5', 'Central bank bonds'), ('6', 'Corporate bonds'), ('7', 'MFO bonds'), ('8', 'Exchange-traded bonds'), ('9', 'Shares of open MIF'), ('A', 'Shares of interval MIF'), ('B', 'Shares of closed MIF'), ('C', 'Municipal bonds'), ('D', 'Depository receipts'), ('E', 'Securities of exchange investment funds (ETFs)'), ('F', 'Mortgage certificate'), ('G', 'A basket of securities'), ('H', 'Additional list ID'), ('I', 'ETC (commodity instruments)'), ('U', 'Clearing certificates of participation'), ('Q', 'Currency'), ('J', 'A share of stock exchange MIF')], default='1', help_text='The type of security.', max_length=1, null=True, verbose_name='sectype'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='settledate',
            field=models.DateField(help_text='Settlement date of the transaction.', null=True, verbose_name='settledate'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shortname',
            field=models.CharField(help_text='The short name of the instrument.', max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('A', 'Operations are allowed'), ('S', 'Operations are prohibited'), ('N', 'Blocked for trading, execution of transactions is allowed')], default='A', help_text='The indicator "trading operations are allowed/prohibited".', max_length=1, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(help_text='The ticker of the stock.', max_length=10, unique=True, verbose_name='ticker'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=18, help_text='The amount of the dividend payment.', max_digits=36, verbose_name='payment')),
                ('registryclosedate', models.DateField(help_text='The date of payment of dividends.', verbose_name='payment date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='stocks_api_v1.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'dividend',
                'verbose_name_plural': 'dividends',
                'ordering': ('-registryclosedate',),
            },
        ),
    ]
